### ISSUE TITLE
NTR: Request for S06 One-way travel time

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#10]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>One-way travel time <p><b>Definition</b><p> The time taken for an acoustic  signal to travel from its source to a reflecting or refracting surface.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.geoexpro.com/articles/2018/05/a-simple-guide-to-seismic-depth-conversion-i https://www.glossary.oilfield.slb.com/en/Terms/t/two-way_traveltime.aspx https://oceanexplorer.noaa.gov/technology/tools/sonar/sonar.html<p> <b>Mapping to other terminologies </b><p> For migration to GP_MODEL of: http://vocab.nerc.ac.uk/collection/P01/current/STRVIO01/<p>

**Comment by gwemon** [comment]
@danibodc term published http://vocab.nerc.ac.uk/collection/S06/current/S0600256/
