### ISSUE TITLE
NTR: Request for S06 Location (geographic coordinates)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#11]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Location (geographic coordinates) <p><b>Definition</b><p> A location relative to the surface of the Earth, or other planetary or stellar body, represented by a point, line, arc, or any other type of polygon and defined by encoding the coordinates of the location in a known Coordinate Reference System. Where possible the Coordinate Reference System used should be specified elsewhere in the metadata by a term from a well defined and managed register such as the European Petroleum Survey Group (EPSG) Geodetic Parameter Dataset.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/33<p>

**Comment by gwemon** [comment]
Term published http://vocab.nerc.ac.uk/collection/S06/current/S0600255/
