### ISSUE TITLE
NTR: Request for S06 Equivalent Spherical Diameter

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#12]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Equivalent spherical diameter <p><b>Definition</b><p> The diameter of a spherical particle which will give identical geometric, optical, electrical or aerodynamic behaviour to that of the particle (non-spherical) being examined; sometimes referred to as the Stokes diameter for particles in non-turbulent flows (Source: IUPAC, 1990. Glossary of atmospheric chemistry terms (Recommendations 1990), https://doi.org/10.1351/pac199062112167 )<p><H2> Optional </H2><p><b>Sources/references</b><p> Jennings, B. R. and Parslow, K. (1988) Particle Size Measurement: The Equivalent Spherical Diameter. Proceedings of the Royal Society of London. Series A 419, 137-149http://thesauri.lifewatchitaly.eu/PhytoTraits/index.php?tema=18&/equivalent-spherical-diameterhttps://goldbook.iupac.org/terms/view/E02191<p> <b>Synonym or acronym (AltLabel)</b><p> ESD<p>

**Comment by gwemon** [comment]
Linked to https://github.com/nvs-vocabs/P01/issues/37

**Comment by danibodc** [comment]
A new S06 term has now been created:

S0600260 - Equivalent spherical diameter

Description: The diameter of a spherical particle of equivalent volume which will give identical geometric, optical, electrical or aerodynamic behaviour to that of the particle (non-spherical) being examined, sometimes referred to as the Stokes diameter for particles in non-turbulent flows (Source: IUPAC (1990), https://doi.org/10.1351/pac199062112167).

It will become live on the NVS after the database refresh from 1400UTC.

**Comment by danibodc** [comment]
This is now live on the NVS: 
http://vocab.nerc.ac.uk/collection/S06/current/S0600260/
