### ISSUE TITLE
NTR: Request for S06 Radial velocity (away from)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Radial velocity (away from) <p><b>Definition</b><p> The rate at which matter or an object moves away from a reference point along a line connecting the reference point to the moving object or particle of matter. In radar technology it is the component of the target''s motion that is along the radar beam.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-368 (https://github.com/nvs-vocabs/P01/issues/49)<p> <b>ORCID</b><p> https://orcid.org/0000-0001-6559-4178<p> <b>Mapping to other terminologies </b><p> Has broad match: http://qudt.org/vocab/quantitykind/Velocity<p>

**Comment by gwemon** [comment]
New term added to S06: http://vocab.nerc.ac.uk/collection/S06/current/S0600265/
