### ISSUE TITLE
NTR: Request for S06 Duration

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#18]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Duration <p><b>Definition</b><p> The length of time that something lasts.<p><H2> Optional </H2><p><b>Sources/references</b><p> e.g. http://vocab.nerc.ac.uk/collection/P01/current/AZDRZZ01/<p> <b>ORCID</b><p> 0000-0001-6559-4178<p> <b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/P24/current/TIME/<p>

**Comment by dr-shorthair** [comment]
https://www.w3.org/TR/owl-time/#duration

**Comment by gwemon** [comment]
Created and Queued for overnight publication - changed "length of time" to "amount of time" in definition.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600331/
