### ISSUE TITLE
NTR: Request for S06 Biomass as nitrogen (BODCNVS-1000)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Biomass as nitrogen <p><b>Definition</b><p> Mass of living biological organisms measured or expressed as the mass of organically bound nitrogen.<p><H2> Optional </H2><p><b>ORCID</b><p> gwemon (github ID)<p> <b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/P24/current/NMASS/<p>

**Comment by gwemon** [comment]
NTR needed to support creation of e.g. nvs-vocabs/P01#43

**Comment by dr-shorthair** [comment]
@markebaird I think this is the one that [you suggest](https://github.com/nvs-vocabs/P01/issues/46#issuecomment-771291561) should be 

> Biomass as **model** nitrogen

**Comment by dr-shorthair** [comment]
@markebaird do we need to suggest a specialization for **model** nitrogen?

**Comment by gwemon** [comment]
@dr-shorthair please see my comment https://github.com/nvs-vocabs/P01/issues/46#issuecomment-827159434 which relates to this suggestion.

**Comment by dr-shorthair** [comment]
Sorry - yes _ just saw your other comment. This is very timely progress as I am meeting with @markebaird tomorrow. 

We have a range of mappings from eReefs usage to NVS proposed. I'm a bit confused in some places about which NVS vocab to choose. I'm leaning towards the S0X series in general as I understand that they are the most systematic ... is that your judgement?

**Comment by gwemon** [comment]
Not sure I understand wht you mean by the "most systematic". In comparison to what? The S0X vocabs are the building blocks of a P01 term. Once all the S0X concepts needed to define the variable have been identified then they can be combined into a P01 code. Happy to work on example mappings with you if required.

**Comment by dr-shorthair** [comment]
Our current draft mappings are documented here: https://bitbucket.csiro.au/projects/ER/repos/ereefs-vocabulary-mappings/browse/ereefs.ttl 
If you can make sense of that and critique it would be appreciated

(But it may be a private repo - not sure)

**Comment by danibodc** [comment]
New S06 term created:

New term created:

S0600271 - Biomass as nitrogen	
Mass of living biological organisms measured or expressed as the mass of organically bound nitrogen.

This will not become live on the NVS until tomorrow AM after the overnight database refresh.

**Comment by danibodc** [comment]
This term is now published:
http://vocab.nerc.ac.uk/collection/S06/current/S0600271/
