### ISSUE TITLE
NTR: Request for Area (in digital image) (BODCNVS-1876)

### ISSUE THREAD

**Issue by PatriciaCabrera** [nvs-vocabs/S06#21]
### Term name (PrefLabel)
Area (in digital image)
### Definition
The total surface area (length*length) of an object captured in a digital image and normally expressed in µm2 or mm2.
### Sources/references
http://thesauri.lifewatchitaly.eu/PhytoTraits/index.php?tema=16&/surface-area
Gorsky et. al. 2010, https://doi.org/10.1093/plankt/fbp124

### Mapping to external terminologies
http://vocab.nerc.ac.uk/collection/P24/current/AREA/1/
### ORCID
https://orcid.org/0000-0003-3293-5612

**Comment by gwemon** [comment]
@PatriciaCabrera I am unsure about this one. If it is expressed in um2 or mm2 then I guess this is an estimate of the real size of the object? If this is the case then we should not specify (in digital image) in the property. However I can understand that simply stating "Area of biological entity specified elsewhere" is ambiguous and not very accurate. Are you aware of the terminology used in digital image processing for this kind of, what I imagine to be, a derived parameter? is it simply the area measured as seen in the digital image in pixel^2 and then extrapolated to real size in um^2 or mm^2?

**Comment by PatriciaCabrera** [comment]
@gwemon adding here Jean-Olivier Irisson @jiho who can help in answering this question.

**Comment by jiho** [comment]
@gwemon Indeed, the measurement is in pixel^2 and then converted. We just discussed this and realised that, for consistency with Length (http://vocab.nerc.ac.uk/collection/P01/current/LGPIXEL1/) and Width, it would be better to keep it in pixels here too.

Then we have asked experts in digital imaging for the most canonical terminology regarding what we commonly call "area". We will get back to you with an updated specification for the term ASAP.

**Comment by PatriciaCabrera** [comment]
@jiho & @gwemon  Now that Length (expressed as pixels) has been created (http://vocab.nerc.ac.uk/collection/P01/current/LGPIXEL1/), I wonder if it is more clear to define Area and to semantically link these terms?

**Comment by jiho** [comment]
It took me a long time to get back on this but I did not forget (well I did but my TODO software reminded me!).

So it looks like a common and well understood + precise term would be "silhouette area" (of an object in digital image).

**Comment by PatriciaCabrera** [comment]
@jiho do we still need this: "silhouette area" (of an object in digital image)?

**Comment by jiho** [comment]
I think it would be useful, yes. We have length and width in pixels, we can have area in pixels too. These are some of the most ecologically important measurements we do on images.
From OBIS' point of view, they will only be useful for datasets provided at individual level but some people are starting to provide those so it is relevant.

**Comment by PatriciaCabrera** [comment]
Oh but I see we have Area in pixels: https://vocab.nerc.ac.uk/collection/P01/current/ARPIXEL2/.

**Comment by gwemon** [comment]
@PatriciaCabrera  This code (https://vocab.nerc.ac.uk/collection/P01/current/ARPIXEL2/) is the area of the pixel itself rather than the Area of an object in pixel^2.
We can create a new S06 for "Area (expressed as pixels)" and combine it to create a new P01 with Preflabel: "Area (expressed as pixels) of biological entity specified elsewhere".

**Comment by PatriciaCabrera** [comment]
@gwemon True! I read it too quickly. Indeed we need: "Area (expressed as pixels) of biological entity specified elsewhere". Can you please create it? Thanks!

**Comment by jakjonbodc** [comment]
Created new S06 term for 'Area (expressed as pixels)' - S0600316

http://vocab.nerc.ac.uk/collection/S06/current/S0600316/

**Comment by jakjonbodc** [comment]
Created new P01 term for 'Area (expressed as pixels) of biological entity specified elsewhere' - APIXBI01

http://vocab.nerc.ac.uk/collection/P01/current/APIXBI01/
