### ISSUE TITLE
NTR: Request for S06 Latent heat flux (BODCNVS-339)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#26]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Latent heat flux <p><b>Definition</b><p> The heat used to evaporate water from the ocean surface, resulting in ocean cooling, which is then released to warm the atmosphere when the vapour condenses to form clouds.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://journals.ametsoc.org/view/journals/clim/30/1/jcli-d-16-0285.1.xml<p> <b>ORCID</b><p> 49520162<p>

**Comment by roy-lowry** [comment]
My suggestion for a definition that includes the definition of flux.

The quantity of energy per unit area per unit time lost from the ocean surface resulting in ocean cooling that is subsequently released to warm the atmosphere when the vapour condenses to form clouds.

**Comment by gwemon** [comment]
S0600266 queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600266/
