### ISSUE TITLE
NTR: Request for S06 Friction velocity (BODCNVS-339)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#27]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Friction velocity <p><b>Definition</b><p> A way of expressing shear stress in units of velocity. Defined as the square root of shear stress divided by fluid density, it is used in fluid mechanics to compare true velocities to a velocity that relates to shear between layers of flow. It is also known as shear velocity.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.aiche.org/ccps/resources/glossary/process-safety-glossary/friction-velocity-uhttps://www.thermopedia.com/content/790/https://www.sciencedirect.com/topics/engineering/friction-velocity<p> <b>ORCID</b><p> roswri<p>

**Comment by gwemon** [comment]
We have 3 existing P01 codes related to "Friction velocity": 2 in the atmosphere and 1 for waves on the water body. All three will need remodelling using the new semantic model.

While http://vocab.nerc.ac.uk/collection/P01/current/FRVMOD01/ explicitly states "Friction velocity of waves on the water body", the other 2 do not specify any objects (see e.g. http://vocab.nerc.ac.uk/collection/P01/current/FVIDSOP1/). Should this not be wind? and should it be wind (at 10 metres). 
If so then we could remodel the codes as follows:
Friction velocity of [wind (at 10 metres)](http://vocab.nerc.ac.uk/collection/S29/current/PE001250/) in the [atmosphere](http://vocab.nerc.ac.uk/collection/S26/current/MAT00843/) by [port-mounted sonic anemometer](http://vocab.nerc.ac.uk/collection/S04/current/S041167/] and [computation using the Inertial Dissipation method and wind velocity corrected to a height of 10m]

We will need a new S05 entry for the processing method "computation using the Inertial Dissipation method and wind velocity corrected to a height of 10m"

For shipboard method reference see: https://journals.ametsoc.org/view/journals/atot/11/4/1520-0426_1994_011_1093_tuotid_2_0_co_2.xml

**Comment by gwemon** [comment]
Same as: "Shear velocity" (e.g. https://en.wikipedia.org/wiki/Shear_velocity)

**Comment by gwemon** [comment]
Thank you @roswri new S06 code **S0600268	Friction velocity** added and queued for publication on the NVS shortly after 0700AM UTC

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600268/
