### ISSUE TITLE
NTR: Request for S06 Size category (BODCNVS-989)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#28]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Size category <p><b>Definition</b><p> Terms used in the contruction of a complex variable description when the objects of interest need to be grouped according to their size. These categories may be expressed as text (e.g. "small", "large") or size intervals (e.g. ">200um", "20-20um"). It is recommended that the result be constrained by a controlled vocabulary such as [S09](http://vocab.nerc.ac.uk/collection/S09/current/) for biological objects.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/65<p>

**Comment by gwemon** [comment]
Hi @danibodc could you add this one in S06 please? Thank you.

**Comment by danibodc** [comment]
Hi @gwemon 

I have now created this S06 term:

S0600270	Size category 

Terms used in the construction of a complex variable description when the objects of interest need to be grouped according to their size. These categories may be expressed as text (e.g. "small", "large") or size intervals (e.g. ">200um", "20-20um"). It is recommended that the result be constrained by a controlled vocabulary such as [S09] (http://vocab.nerc.ac.uk/collection/S09/current/) for biological objects.

**Comment by dr-shorthair** [comment]
What is the relationship of this to 
http://vocab.nerc.ac.uk/collection/S06/current/S0600192/ and 
http://vocab.nerc.ac.uk/collection/S06/current/S0600089/ ??

**Comment by gwemon** [comment]
@dr-shorthair the new term is a nominal property category; that means that any P01 code built with this S06 property would have a character string result.
The S06 concept ["Size class"](http://vocab.nerc.ac.uk/collection/S06/current/S0600089/ ) clearly states that it is "a size interval defined as a character string indicating the lower size limit, the upper size limit and the unit of measurement of the upper and lower limits."; so it would not accept text categories like e.g. "small"/"medium"/"large" terms that are often used in e.g. plankton samples counted using optical microscopy.
Same for the other S06 concept ["Grain-size"](http://vocab.nerc.ac.uk/collection/S06/current/S0600192/). "Grain-size" is a legacy term somewhat, inherited from the old version of the P01 parameter dictionary. I have often wondered if it should not be replaced by "Equivalent Spherical Diameter". This might be something worth discussing with sedimentologists at some stage and also comparing with the way other terminologies have defined or labelled these concepts.

**Comment by dr-shorthair** [comment]
OK - should 'grain-size' be seen as a specialization of the new term? 
Should 'size-class' be a generalization??

**Comment by gwemon** [comment]
I see the new term as the more generic term of all 3, and size-class and "grain-size" may be seen as specialisations with the difference that "grain-size", unlike the other 2, is a quantity whose result is a numerical value that needs to be linked to a unit unlike the other 2 for which the result will be text (preferably constrained by a controlled vocabulary but it could also be free text, depending on how we define the P01 code).
