### ISSUE TITLE
NTR: Request for S06 Biomass as carbon (BODCNVS-936)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#29]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Biomass as carbon <p><b>Definition</b><p> Mass of living biological organisms measured or expressed as the mass of organically bound carbon.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
New term created:

S0600272 - Biomass as carbon	
Mass of living biological organisms measured or expressed as the mass of organically bound carbon.

This will not become live on the NVS until tomorrow AM after the overnight database refresh.

**Comment by danibodc** [comment]
This term is now published:
http://vocab.nerc.ac.uk/collection/S06/current/S0600272/
