### ISSUE TITLE
NTR: Request for S06 Sequence number (BODCNVS-1083)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#34]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Sequence number <p><b>Definition</b><p> A number belonging to an ordered list of numbers. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/83<p>

**Comment by danibodc** [comment]
The above term has now been created:

**Code:** S0600275	
**Preferred label:** Sequence number	
**Description:** A number belonging to an ordered list of numbers.

It will be live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
This code is now live:
https://vocab.nerc.ac.uk/collection/S06/current/S0600275/
