### ISSUE TITLE
NTR: Request for S06 Enrichment with respect to VCDT

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#40]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Enrichment with respect to VCDT <p><b>Definition</b><p> The change in the relative abundance of an isotope of a given element relative to its relative abundance in the Vienna Canyon Diablo Troilite (VCDT) international measurement standard, also known as IAEA-S-1 and formerly known as NZ-1 (NIST 8554), a reference material for relative sulfur isotope ratio measurements.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/%CE%9434Shttps://www-s.nist.gov/srmors/certificates/8554.pdfhttps://github.com/nvs-vocabs/P01/issues/72<p>

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600282/ published on NVS
