### ISSUE TITLE
NTR: Request for S06 Total alkalinity

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#41]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Total alkalinity <p><b>Definition</b><p> The acid-neutralising capacity of solutes in an aqueous system or sample.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://pubs.usgs.gov/twri/twri9a6/twri9a66/twri9a_6.6.pdf<p> <b>Synonym or acronym (AltLabel)</b><p> TA<p>

**Comment by danibodc** [comment]
This term is now live on the NVS:
https://vocab.nerc.ac.uk/collection/S06/current/S0600283/
