### ISSUE TITLE
NTR: Request for S06 Saturation state

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#42]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Saturation state <p><b>Definition</b><p> A measure of the thermodynamic potential for a mineral to form or to dissolve<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/115<p>

**Comment by roswri** [comment]
Term submitted via vocab editor (I don't seem to have permissions to insert terms directly to S06 in SQL developer).
S0600284 - Saturation state

**Comment by roswri** [comment]
Term confirmed to be on the NVS:
http://vocab.nerc.ac.uk/collection/S06/current/S0600284/
