### ISSUE TITLE
NTR: Request for S06 Relative humidity (BODCNVS-740)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#43]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Relative humidity <p><b>Definition</b><p> The ratio of the amount of water vapour in the air compared to the maximum amount of water vapour that can theoretically be held at the air's temperature.<p><H2> Optional </H2><p><b>Mapping to other terminologies </b><p> http://www.ontology-of-units-of-measure.org/resource/om-2/RelativeHumidityhttps://unterm.un.org/unterm/display/record/wmo/na?OriginalId=f3acc9e3-4177-4706-a880-5f582c92befa<p>

**Comment by danibodc** [comment]
The above term has been loaded and will be live on the NVS from 0730 UTC tomorrow morning:

S0600297 - Relative humidity

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600297/
