### ISSUE TITLE
NTR: Request for S06 Dew-point temperature (BODCNVS-740)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#44]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Dew-point temperature <p><b>Definition</b><p> The temperature to which air must cool to become saturated with water vapour.<p><H2> Optional </H2><p><b>Mapping to other terminologies </b><p> https://unterm.un.org/unterm/display/record/wmo/na?OriginalId=3d02b1e9-a4b1-46ac-aeb1-1afccd08e2bd<p>

**Comment by danibodc** [comment]
The above term has been loaded and will be live on the NVS from 0730 UTC tomorrow morning.

S0600296 - Dew-point temperature

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600296/
