### ISSUE TITLE
NTR: Relative loss rate 

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/S06#45]
### Term name (PrefLabel)
Relative loss rate
### Definition
The rate at which the quantity of an entity decreases.

### Sources/references
To be modelled similar to existing terms, e.g. particularly S0600009: Evacuation Rate The rate at which an organism disposes of a substance as solid waste.

### Synonym or acronym (AltLabel)
n/a
### Mapping to external terminologies
n/a
### ORCID
n/a
### Additional information
n/a

**Comment by gwemon** [comment]
@JordanAthertonNOC  the definition of "Loss rate" in S06 needs to be applicable to any kind of loss rate i.e. not just the loss rate of zooxanthellae from corals. Have a look at the definition of other rates in S06 to see examples of how to define the new term.

**Comment by JordanAthertonNOC** [comment]
One new S06 term created, anticipated to go live on the NVS at ~07:00 BST tomorrow.
[S0600293](https://vocab.nerc.ac.uk/collection/S06/current/S0600293/)
Relative loss rate
The amount of an entity lost from a system divided by the initial amount of that entity in the system relative to time.
