### ISSUE TITLE
NTR: Request for S06 Remote sensing reflectance

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#46]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Remote sensing reflectance <p><b>Definition</b><p> The ratio of water-leaving radiance (Lw, units: µW cm−2 sr−1 nm−1) to downwelling irradiance just above the sea surface (Es, units: µW cm−2 nm−1) (O’Reilly et al., 1998).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://oceancolor.gsfc.nasa.gov/atbd/rrs/https://github.com/nvs-vocabs/P01/issues/125<p>

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600285/
