### ISSUE TITLE
NTR: Request for S06 Biochemical Oxygen Demand

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#50]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Biochemical Oxygen Demand <p><b>Definition</b><p> The amount of dissolved oxygen needed by aerobic biological organisms to break down organic material present in a given water sample at certain temperature over a specific time period.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/biochemical-oxygen-demand<p> <b>Synonym or acronym (AltLabel)</b><p> Biological oxygen demand<p>

**Comment by roswri** [comment]
Definition of existing P01 (https://vocab.nerc.ac.uk/collection/P01/current/BODZZZZZ/): The quantity of dissolved oxygen consumed per unit volume of a sample of any body of fresh or salt water during 5 days of incubation at 20C

**Comment by roswri** [comment]
S0600287 - Biochemical oxygen demand 
submitted via vocab editor

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600287/
