### ISSUE TITLE
NTR: Request for S06 Chemical Oxygen Demand

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#51]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Chemical Oxygen Demand <p><b>Definition</b><p> The amount of oxygen that is needed to oxidise the organic matter present in a quantity of water.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.sciencedirect.com/topics/earth-and-planetary-sciences/chemical-oxygen-demand<p>

**Comment by roswri** [comment]
Definition of existing P01 (https://vocab.nerc.ac.uk/collection/P01/current/CODZZZZZ/):
Quantity of oxygen required to oxidize all dissolved oxidizable chemical material contained in a unit volume of a water body. Solute may be expressed in terms of mass, volume or quantity of substance.

**Comment by roswri** [comment]
S0600288 - Chemical oxygen demand
submitted via vocab editor

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600288/
