### ISSUE TITLE
NTR: Request for S06 Photochemical oxygen demand

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#52]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Photochemical oxygen demand <p><b>Definition</b><p> The amount of oxygen that is needed to oxidise all dissolved oxidisable chemical material contained in a unit volume of a water body under the influence of radiant energy (such as light).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.researchgate.net/publication/255467943_Photochemical_oxygen_consumption_in_marine_waters_A_major_sink_for_colored_dissolved_organic_matterhttps://www.merriam-webster.com/dictionary/photooxidation<p>

**Comment by roswri** [comment]
S0600289 - Photochemical oxygen demand 
submitted via vocab editor

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600289/
