### ISSUE TITLE
NTR: Request for S06 Vertical attenuation

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#54]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Vertical attenuation <p><b>Definition</b><p> The proportion of any kind of flux or signal that is lost when absorbed or scattered by a medium along the vertical Z axis.<p><H2> Optional </H2><p><b>Sources/references</b><p>nvs-vocabs/P01/issues/157<p>

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from tomorrow morning.

**Comment by danibodc** [comment]
This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S06/current/S0600292/
