### ISSUE TITLE
NTR: Request for S06 Density (dry bulk) (BODCNVS-1232)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#57]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Density (dry bulk) <p><b>Definition</b><p> Mass of dry matter contained in a sample of soil or sediment divided by the volume of the sample before drying.  <p><H2> Optional </H2><p><b>Sources/references</b><p> adapted from https://en.wikipedia.org/wiki/Bulk_density<p>

**Comment by gwemon** [comment]
term created and queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600299/
