### ISSUE TITLE
NTR: Request for S06 Density (wet bulk) (BODCVS-1232)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#58]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Density (wet bulk) <p><b>Definition</b><p> Total mass of a fresh sample of soil or sediment (solid plus water) divided by its volume.<p><H2> Optional </H2><p><b>Sources/references</b><p> adapted from https://en.wikipedia.org/wiki/Bulk_density<p>

**Comment by gwemon** [comment]
term created and queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600300/
