### ISSUE TITLE
NTR: Request for S06 Surface elevation

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S06#6]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Surface elevation <p><b>Definition</b><p> The height above or below a fixed reference point.<p><H2> Optional </H2><p>

**Comment by roy-lowry** [comment]
I would prefer 'The vertical distance of the surface above or below a fixed reference point'. The word height carries the inference of distance above so 'height below' seems a little contradictory.

**Comment by roy-lowry** [comment]
Just realised height implicitly specifies sign convention for the elevation. So how about 'The vertical distance of the surface above (positive values) or below (negative values) a fixed reference point' to keep things explicit in the definition.

**Comment by gwemon** [comment]
Term published http://vocab.nerc.ac.uk/collection/S06/current/S0600259/
