### ISSUE TITLE
NTR: Request for S06 Colour (Pt/Co scale) (BODCNVS-1232)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#62]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Colour (Pt/Co scale) <p><b>Definition</b><p> Also called Alpha-Hazen scale, the Platinum-Cobalt scale is a method of measuring the colour of water samples that is specific to the colour yellow. One unit of colour on the scale is defined as the colour produced by 1 milligram of platinum cobalt dissolved in 1 litre of water.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Pt/Co_scale and originator's information <p>

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600301/
