### ISSUE TITLE
NTR: Request for S06 Horizontal visibility (ESAS code) (BODCNVS-1581)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#63]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Horizontal visibility (ESAS code) <p><b>Definition</b><p> A one-character string used by European Seabirds At Sea (ESAS) to classify ranges of horizontal visibility.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
This term is now live on the NVS:
https://vocab.nerc.ac.uk/collection/S06/current/S0600302/
