### ISSUE TITLE
NTR: Request for S06 Energy level

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#64]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Energy level <p><b>Definition</b><p> A measure of the intensity of echo return from an altimeter or similar acoustic device. Energy level ranges from 0 to 1 where 1 represents full saturation of the receiver. An energy level of 0.707 (square root of 2) is the theoretical perfect level as it represents the energy of a pure sine wave with an amplitude utilising the maximum dynamic range of the receiver.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.impactsubsea.co.uk/wp-content/uploads/2022/11/ISA500-Manual-Rev-2.5.pdf<p>

**Comment by danibodc** [comment]
This term has been loaded to S06 and will be live on the NVS from tomorrow morning:

S0600303	Energy level

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600303/
