### ISSUE TITLE
NTR: Request for S06 Correlation factor

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#65]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Correlation factor <p><b>Definition</b><p> A measure of the quality of the returned pulse from an altimeter or similar acoustic device. Correlation factor ranges from 0 to 1. A value of 1 represents a perfect return echo with negligible noise and distortion.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.impactsubsea.co.uk/wp-content/uploads/2022/11/ISA500-Manual-Rev-2.5.pdf<p>

**Comment by danibodc** [comment]
This term has been loaded to S06 and will be live on the NVS from tomorrow morning:

S0600304	Correlation factor

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600304/
