### ISSUE TITLE
NTR: Request for S06 Areal extent

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#67]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Areal extent <p><b>Definition</b><p> The two-dimensional surface over which an object or a phenomenon is observed. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S06/current/S0600308/
