### ISSUE TITLE
NTR: Request for S06 Coverage (as an area)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#68]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Coverage (as an area) <p><b>Definition</b><p> The two-dimensional surface equivalent to 100% coverage of an object or a phenomenon.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S06/current/S0600307/
