### ISSUE TITLE
NTR: Request for S06 Relative cover category

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#69]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Relative cover category <p><b>Definition</b><p> The proportional coverage of an object or phenomenon divided into class categories like e.g. >75%, <25%, 25-50%<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S06/current/S0600306/
