### ISSUE TITLE
NTR: Request for S06 Amplitude

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#7]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Amplitude <p><b>Definition</b><p> The maximum displacement of a periodic variable over a single spatial or temporal period.<p><H2> Optional </H2><p>

**Comment by gwemon** [comment]
New term added: http://vocab.nerc.ac.uk/collection/S06/current/S0600254/
