### ISSUE TITLE
NTR: Request for S06 Relative humidity

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#71]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Relative humidity <p><b>Definition</b><p> The ratio of the amount of water vapour in the air compared to the maximum amount of water vapour that can theoretically be held at the air's temperature<p><H2> Optional </H2><p><b>Sources/references</b><p> https://vocab.nerc.ac.uk/collection/P01/current/CRELZZ01/<p> <b>Mapping to other terminologies </b><p> http://qudt.org/vocab/quantitykind/RelativeHumidity<p>

**Comment by gwemon** [comment]
Needed for legacy code "migration" i.e. remodelling of all remaining P01 codes according to the PUV semantic model.

**Comment by gwemon** [comment]
Term created with mapping to QUDT. All queued for overnight publication:
http://vocab.nerc.ac.uk/collection/S06/current/S0600323	has-exact-match	http://qudt.org/vocab/quantitykind/RelativeHumidity
