### ISSUE TITLE
NTR: Request for S06 Dew point temperature

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#72]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Dew point temperature <p><b>Definition</b><p> The temperature to which air must cool to become saturated with water vapour.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://vocab.nerc.ac.uk/collection/P01/current/CDEWZZ01/<p> <b>Mapping to other terminologies </b><p> http://qudt.org/vocab/quantitykind/DewPointTemperature<p>

**Comment by gwemon** [comment]
Term added to NVS in October 2022: https://vocab.nerc.ac.uk/collection/S06/current/S0600296/
Mapping to equivalent QUDT Quantity now added.
