### ISSUE TITLE
NTR: Request for S06 Total alkalinity

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#73]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Total alkalinity <p><b>Definition</b><p> A measure of the proton deficit of a solution relative to an arbitrarily defined zero level of protons (Dickson, 1981). It is expressed in units of concentration representing the amount of acid added as a titrant to a known volume or known mass of solution.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.sciencedirect.com/science/article/abs/pii/0198014981901217<p>

**Comment by gwemon** [comment]
This term was already present in S06: https://vocab.nerc.ac.uk/collection/S06/current/S0600283/ (created in March 2022)
 Please reopen this ticket if the definition needs to be reviewed.
