### ISSUE TITLE
New S06 needed for existing P01 codes 

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S06#75]
We need new S06 for the following existing P01 codes for request https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/32:
[GAK40BED](http://vocab.nerc.ac.uk/collection/P01/current/GAK40BED/) Radiation dose (gamma) of potassium-40 {40K CAS 13966-00-2} from the bed
[ACTVM010](http://vocab.nerc.ac.uk/collection/P01/current/ACTVM010/) Beta activity of potassium-40 {40K CAS 13966-00-2} per unit volume of the water body [unknown phase] by beta spectroscopy
[ACTVM012](http://vocab.nerc.ac.uk/collection/P01/current/ACTVM012/) Beta activity of tritium {3H CAS 10028-17-8} per unit volume of the water body [unknown phase] by scintillation counting

For the last 2 I would suggest creating a S06 for "Beta radiation activity".
Jordan, could you take this on and check if "Radiation dose (gamma)" would be equivalent to "Gamma activity"?

**Comment by roy-lowry** [comment]
Gamma activity and radiation dose (gamma) are different. The former in units like mBq/kg is the number of radioactive decays per unit time per unit mass of a sample. The latter in units like millirad (cgs) or Grays (SI) is a measure of the amount of radioactive energy absorbed by a target. As it's an energy it is a function of the wavelength of the gamma radiation (shorter the wavelength the higher the energy) as well as the rate of decay from the gamma-emitting source.

**Comment by gwemon** [comment]
Thanks @roy-lowry it gives us a good lead! Found the unit Gray in QUDT: https://qudt.org/vocab/unit/GRAY
It's linked to 2 quantity kinds: https://qudt.org/vocab/quantitykind/Kerma and https://qudt.org/vocab/quantitykind/AbsorbedDose 
So we could go with creating a new S06 along the line "Absorbed gamma radiation dose"?
which would help us remodel [GAK40BED](http://vocab.nerc.ac.uk/collection/P01/current/GAK40BED/) to "Absorbed gamma radiation dose of potassium-40 {40K CAS 13966-00-2} from the bed"? 
If we leave it as is then are we saying that this is the radioactive energy emitted by the bed and absorbed by the surrounding environment but the latter is implicit? Would that be correct?

**Comment by roy-lowry** [comment]
'Gamma radiation dose FROM potassium-40 {40K CAS 13966-00-2} IN the bed' works and reads better to me.  'Radiation dose' is a very familiar term to me that says it all.  I also see a risk of 'absorbed' creating a red herring concerning gamma rays passing through the target. Radiation dose is all about the amount of ENERGY arriving at the target and potentially causing it damage.

**Comment by gwemon** [comment]
> 'Gamma radiation dose FROM potassium-40 {40K CAS 13966-00-2} IN the bed' works and reads better to me. 'Radiation dose' is a very familiar term to me that says it all. I also see a risk of 'absorbed' creating a red herring concerning gamma rays passing through the target. Radiation dose is all about the amount of ENERGY arriving at the target and potentially causing it damage.

I see. Yes it makes sense. The problem with your suggestion of using "from" is that we cannot change Property "of" in our semantic model (i.e. Property "of" an object of interest). It would be quite disruptive to do. So, at this stage, I think that we will need to keep it as it was originally constructed and just use the new property (S06)="Gamma radiation dose".

**Comment by roy-lowry** [comment]
OK. Quite used to the semantic model producing less than perfect prose/

**Comment by JordanAthertonNOC** [comment]
Two new S06 terms created:

Gamma radiation dose (http://vocab.nerc.ac.uk/collection/S06/current/S0600310/)
Beta radiation activity (http://vocab.nerc.ac.uk/collection/S06/current/S0600311/)

**Comment by gwemon** [comment]
New S06 terms used in: https://github.com/nvs-vocabs/P01/issues/218
