### ISSUE TITLE
NTR: Request for S06 Relative Penis Size Index

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#77]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Relative Penis Size Index <p><b>Definition</b><p> An index developed to gauge the intensity and effects of imposex, that is the development  of a penis and vas deferens in the female of, for example, gastropods and bivalves, as a result of exposure to certain pollutants. It is defined as the [(mean length of female penis)^3/(mean length of male penis)^3]x100.  This is based on the empuirical observation that the volume or weight of the penis is related to the cube of its length (Bryan et al 1986, Gibbs and Bryan 1987).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/EMODnetChemVocabs/issues/41<p>

**Comment by gwemon** [comment]
Linked to https://github.com/nvs-vocabs/P01/issues/214

**Comment by gwemon** [comment]
New definition: An index used to estimate the intensity of imposex, a condition resulting in the development of a penis and vas deferens in female gastropods when exposed to certain pollutants. The index is calculated as the mean length of female penis cubed divided by mean length of male penis cubed multiplied by 100 (Bryan et al 1986, Gibbs et al 1987, Gibbs 1999).

Acronym: RPSI

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600312/
