### ISSUE TITLE
NTR: Request for S06 Relative Penis Length Index

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#78]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Relative Penis Length Index <p><b>Definition</b><p> An index used in the monitoring of imposex, a condition resulting in the development of a penis and vas deferens in female gastropods when exposed to certain pollutants. The index is calculated as the mean length of female penis divided by mean length of male penis in a population multiplied by 100 (Bryan et al 1986, Gibbs et al 1987, Gibbs 1999).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/214<p>

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600313/
