### ISSUE TITLE
NTR: Request for S06 Vas Deferens Sequence Index

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#79]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Vas Deferens Sequence Index <p><b>Definition</b><p> An index used in the monitoring of imposex, a condition resulting in the development of a penis and vas deferens in female gastropods when exposed to certain pollutants. The index is based on a sequence of six identified stages (number 1 to 6) in the development of imposex in female gastropods plus an initial stage (number 0). The index is the mean of the stages observed in a population  (Gibbs 1999).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/214<p>

**Comment by roswri** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600314/
