### ISSUE TITLE
NTR: Request for S06 Richter Scale magnitude

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#8]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Richter Scale magnitude <p><b>Definition</b><p> The logarithm of the amplitude of seismic waves released during a rupture of Earth's crust (earthquake), recorded by seismographs. Also known as the local magnitude scale (ML), it was developed in 1935 by Charles F. Richter. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.usgs.gov/natural-hazards/earthquake-hazards/science/earthquake-magnitude-energy-release-and-shaking-intensity?qt-science_center_objects=0#qt-science_center_objects https://earthquake.usgs.gov/learn/glossary/?term=Richter%20scale#:~:text=The%20Richter%20magnitude%20scale%20was,of%20waves%20recorded%20by%20seismographs.<p> <b>Synonym or acronym (AltLabel)</b><p> ML<p><b>Mapping to other terminologies </b><p> Migration to GP_MODEL of: http://vocab.nerc.ac.uk/collection/P01/current/RICHTERX/<p>

**Comment by gwemon** [comment]
@danibodc - I would change "Richter scale magnitude" to "Richter magnitude scale" as this is the way it seems to be referred to in the literature.

**Comment by gwemon** [comment]
@danibodc Term published http://vocab.nerc.ac.uk/collection/S06/current/S0600258/
