### ISSUE TITLE
NTR: Relative cover

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S06#83]
Related to: https://github.com/nvs-vocabs/P01/issues/247
Proposed definition based on https://mdm.sandre.eaufrance.fr/node/192687
The contribution of the surface covered by an entity (e.g. a given species, a specific habitat) relative to the sum of contributions from all other considered entities. For example relative cover of zostera or eelgrass relative to the surface covered by all other plants within a surveyed area.

**Comment by danibodc** [comment]
Term is live on the NVS: 
https://vocab.nerc.ac.uk/collection/S06/current/S0600318/
