### ISSUE TITLE
NTR: Request for S06 Volume scattering coefficient

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#84]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Volume scattering coefficient <p><b>Definition</b><p> The radiant intensity of scattered light from a volume element as a function of angle, referred to as Beta. When output from an optical backscattering instrument, Beta is calculated by subtracting dark counts from the raw counts, then multiplying by the manufacturer's supplied calibration scale factor. Units are m-1 sr-1.<p><H2> Optional </H2><p><b>Sources/references</b><p> Sullivan et al (2013), Argo documentation: https://archimer.ifremer.fr/doc/00283/39459/56146.pdf<p> <b>Synonym or acronym (AltLabel)</b><p> Beta<p>

**Comment by gwemon** [comment]
Looks good. @danibodc could you link this to a P01 ticket so that we get the context?

**Comment by danibodc** [comment]
Required as part of https://github.com/nvs-vocabs/P01/issues/249

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from tomorrow morning:
S0600319	Volume scattering coefficient

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600319
