### ISSUE TITLE
NTR: Request for S06 Volume scattering attributable to particles

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S06#85]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Volume scattering attributable to particles <p><b>Definition</b><p> The radiant intensity of scattered light from a volume element as a function of angle, with the contribution of pure seawater removed, referred to as Beta(p). Determined by calculating the volume scattering of pure seawater and removing it from the total volume scattering coefficient (Beta) to yield the volume scattering attributable to particles only. Units are m-1 sr-1.<p><H2> Optional </H2><p><b>Sources/references</b><p> Sullivan et al (2013), Argo documentation: https://archimer.ifremer.fr/doc/00283/39459/56146.pdf<p> <b>Synonym or acronym (AltLabel)</b><p> Beta(p)<p>

**Comment by danibodc** [comment]
Required as part of Required as part of https://github.com/nvs-vocabs/P01/issues/249

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from tomorrow morning:
S0600320	Volume scattering attributable to particles

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/S06/current/S0600320
