### ISSUE TITLE
NTR: Pore size

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S06#88]
Needed for: https://github.com/nvs-vocabs/P01/issues/227

with definition: The dimension (as a length) of the open spaces in a porous material.

**Comment by gwemon** [comment]
@danibodc Maybe one that could be used to check that Sam can create S06 with her new gatekeeper role?

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600325/
