### ISSUE TITLE
NTR: Rate of change

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S06#90]
### Term name (PrefLabel)
Rate of change
### Definition
The speed at which a variable changes over a specific period of time. 
### Sources/references
NA

### Synonym or acronym (AltLabel)
ROC
### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
[Enter your ORCID if desired]
### Additional information
[Any additional information about the new term]

**Comment by danibodc** [comment]
Required as part of https://github.com/nvs-vocabs/P01/issues/257

**Comment by gwemon** [comment]
Thanks @danibodc . The "ROC" acronym seems to come from the fiance domain. I would leave it out to avoid confusion.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S06/current/S0600332/
