### ISSUE TITLE
NTR: Request for 2 new S06 terms Bathymetric depth and Topographic Height

### ISSUE THREAD

**Issue by SLBlakeman** [nvs-vocabs/S06#92]
Creation of 2 new S06 terms in order to migrate Sea-floor P01 terms as explained here: https://github.com/nvs-vocabs/P01/issues/213#

New terms will be available on the NVS in the morning of 13/09/2024:

[S0600335](http://vocab.nerc.ac.uk/collection/S06/current/S0600335) Topographic height - The measurement of the elevation of the Earth's surface above a datum. 
[S0600334](http://vocab.nerc.ac.uk/collection/S06/current/S0600334) Bathymetric depth - The measurement of the depth of a body of water, such as an ocean, lake, or river.

**Comment by dr-shorthair** [comment]
Hmm. 
1. "Elevation" is the more common term used in Geodesy. (Rather than "Height", which can measure a vertical extent.)
2. "Depth" usually refers to the vertical offset of a point, measured relative to a datum, measured positive downwards. The concept you describe is better named "thickness" or "layer thickness",.

**Comment by gwemon** [comment]
Thank you for the comments @dr-shorthair. You are right and we will link our terms to these terms using mappings to authoritative sources of physical properties. However our main objective here was to create a new entries in the S06 vocabulary that could be used to remodel our existing "Sea-floor height" and "Sea-floor depth" P01 codes (see full and long considerations about this here: https://github.com/nvs-vocabs/P01/issues/213). Topographic height and Bathymetric depth was a good compromise which received approval from GEBCO's experts.
